version: "3.7"
services:
  cowrie:
    image: cowrie/cowrie:latest
    configs:
      - source: cowrie_cfg
        target: /etc/cowrie.cfg
    ports:
      - "2222:2222/tcp"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 5s
        failure_action: pause
        monitor: 5s
        max_failure_ratio: 0
        order: start-first

configs:
  cowrie_cfg:
    external: true
