#------------------ LOCAL REGISTRY CONFIGURATION V 1.0 ------------------#
# Located at /etc/docker/registry/config.yml
# File ownership: [user]:[]group]
# File permissions: []755]
#
#---------- VERSION HISTORY
# V 1.0     Initial
#------------------------------------------------------------------------#
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :55443
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://ip:port']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Max-Age: [1728000]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
  username: [username]
  password: [password]