services:
  autoheal:
    image: willfarrell/autoheal:${AUTOHEAL_TAG:-latest}
    container_name: Autoheal
    hostname: autoheal
    read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 12M
        reservations:
          memory: 6M
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=1
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      - DOCKER_SOCK=/var/run/docker.sock
      - CURL_TIMEOUT=30
      - WEBHOOK_URL=$AUTOHEAL_HOOK
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - autoheal:true
    networks:
      - docker
    logging:
      options:
        #syslog-address: "udp://192.168.68.5:514"
        max-size: 50m
        max-file: 10

  code-server:
    image: lscr.io/linuxserver/code-server:${CODESERVER_TAG:-latest}
    container_name: Code-Server
    hostname: codeserver
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          #cpus: '1.0'
          memory: 1G
        reservations:
          #cpus: '0.5'
          memory: 500M
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TZ
      - DEFAULT_WORKSPACE=$WORKSPACE
      - INSTALL_PACKAGES=make|wget|curl
      - DOCKER_MODS=$CODESERVER_DOCKER_MODS
      - VSCODE_EXTENSION_IDS=$CODESERVER_EXTENSIONS
    volumes:
      - $USERDIR/code-server:/config:rw
      - $USERDIR:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - autoheal:true
    ports:
      - ${CODE_SERVER_PORT:-8443}:8443
    networks:
      - docker
    logging:
      options:
        #syslog-address: "udp://192.168.68.5:514"
        max-size: 50m
        max-file: 10

  theme-park:
    image: ghcr.io/gilbn/theme.park:${THEMEPARK_TAG:-latest}
    container_name: Theme-Park
    hostname: themepark
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          #cpus: '0.1'
          memory: 50M
        reservations:
          #cpus: '0.05'
          memory: 35M
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TZ
      - TP_URL_BASE=themepark
    volumes:
      - $USERDIR/theme-park:/config:rw
    labels:
      - autoheal:true
    ports:
      - ${THEMPARK_HTTP_PORT:-8080}:80
      - ${THEMPARK_HTTPS_PORT:-4443}:443
    networks:
      - docker
    logging:
      logging:
      options:
        #syslog-address: "udp://192.168.68.5:514"
        max-size: 50m
        max-file: 10

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_TAG:-latest}
    container_name: Watchtower
    hostname: watchtower
    read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 96M
        reservations:
          memory: 48M
    environment:
      - TZ=$TZ
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=$WATCHTOWER_API_TOKEN
      - WATCHTOWER_SCHEDULE=$WATCHTOWER_SCHEDULE
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LOG_LEVEL=debug
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_LABEL_ENABLE=false # Update containers that have a `com.centurylinklabs.watchtower.enable` label set to true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - autoheal:true
    ports:
      - ${WATCHTOWER_HTTP_API_PORT:-8080}:8080
    networks:
      - docker
    logging:
      options:
        #syslog-address: "udp://192.168.68.5:514"
        max-size: 50m
        max-file: 10


#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true
