services:
  tubearchivist:
    image: bbilly1/tubearchivist:${TA_TAG:-latest}
    container_name: Tube-Archivist
    hostname: tubearchivist
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          #cpus: '0.75'
          memory: 750M
        reservations:
          #cpus: '0.1'
          memory: 50M
    environment:
      - TZ=$TZ
      - HOST_UID=$UID
      - HOST_GID=$GID
      - ES_URL=http://${TA_HOST}:${ES_PORT}
      - TA_HOST=${TA_HOST}
      - TA_USERNAME=${TA_UN}
      - TA_PASSWORD=${TA_PW}
      - REDIS_HOST=archivist-redis
      - ELASTIC_PASSWORD=${ES_PW}
    ports:
      - ${TA_PORT:-8000}:8000
    volumes:
      - $MEDIADIR:/youtube:rw
      - $USERDIR/cache:/cache:rw
      - $TA_IMPORT:/cache/import:rw
      - $BACKDIR:/backups:rw
    labels:
      - autoheal:true
    networks:
      - docker
      - archivist
    logging:
      options:
        max-size: 50m
    depends_on:
      - archivist-es
      - archivist-redis

#----- REDIS
  archivist-redis:
    image: redis/redis-stack-server:${REDIS_TAG:-latest}
    container_name: TA-Redis
    hostname: taredis
    read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          #cpus: '0.5'
          memory: 512M
        reservations:
          #cpus: '0.05'
          memory: 128M
    volumes:
      - $USERDIR/redis:/data:rw
    expose:
      - 6379
    labels:
      - autoheal:true
    networks:
      - archivist
    depends_on:
      - archivist-es

#----- ELASTIC SEARCH -> DOES NOT WORK!
  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG:-latest}
    container_name: TA-ESearch
    hostname: taesearch
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          #cpus: '1.5'
          memory: 750M
        reservations:
          #cpus: '0.5'
          memory: 500M
    environment:
      - ELASTIC_PASSWORD=${ES_PW}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    volumes:
      - $USERDIR/es:/usr/share/elasticsearch/data:rw
    ports:
      - ${ES_PORT:-9200}:9200
    labels:
      - autoheal:true
    networks:
      - archivist


#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true
  archivist:
    name: $ARCHIVIST_NET
    external: false