services:
  joplin-db:
    image: postgres:14.1-alpine
    container_name: Joplin-DB
    hostname: joplindb
    restart: unless-stopped
    ports:
      - $POSTGRESS_PORT:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
      - $USERDIR/joplin/database:/var/lib/postgresql/data

  joplin-app:
    image: joplin/server:latest
    container_name: Joplin
    hostname: joplin
    restart: unless-stopped
    depends_on:
      - joplin-db
    ports:
      - $JOP_PORT:22300
    environment:
      - APP_PORT=$JOP_PORT
      - APP_BASE_URL=$APP_BASE_URL
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=joplin-db

#============= COMMON
networks:
  default:
    external: true
    name: $DOCKER_NETWORK
