version: "3"
services:
  homer:
    image: b4bz/homer
    container_name: Homer
    restart: unless-stopped
    hostname: homer
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 8070:8080
    volumes:
      - /home/pi/homer:/www/assets
    logging:
      options:
        max-size: 50m

  Node-Red:
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    hostname: nodered
    ports:
      - 1880:1880
    volumes:
      - /home/pi/homer/nodered:/data
    logging:
      options:
        max-size: 50m

networks:
  default:
    external: true
    name: styx
