services:
  uptime-kuma:
    image: louislam/uptime-kuma:debian
    container_name: Uptime-Kuma
    hostname: kuma
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 5
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_SETGID
      - CAP_NET_RAW
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.10
    mem_limit: 24m
    mem_reservation: 10m
    ports:
      - $KUMA_PORT:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=HostRegexp(`kuma.{ip:.*}.traefik.me`)"
      - "traefik.http.routers.kuma.rule=Host(`kuma.traefik.me`)"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.routers.kuma-tls.tls.domains[0].main=kuma.traefik.me"
      - "traefik.http.routers.kuma-tls.tls.domains[0].sans=kuma-*.traefik.me"
    volumes:
      - $USERDIR/uptime-kuma:/app/data
    logging:
      options:
        max-size: 50m

  #----------------- PROMETHEUS
  Prometheus:
    image: prom/prometheus:latest
    container_name: Prometheus
    hostname: prometheus
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 5
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.10
    mem_limit: 24m
    mem_reservation: 10m
    ports:
      - $PROMETHEUS_PORT:9090
    labels:
      - "traefik.enable=false"
    volumes:
      - $USERDIR/prometheus:/etc/prometheus
      - $USERDIR/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    logging:
      options:
        max-size: 50m

  alert-manager:
    image: quay.io/prometheus/alertmanager
    container_name: Alert-Manager
    hostname: altermanager
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 3
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    ports:
      - $AM_PORT:9093
    labels:
      - "traefik.enable=false"
    volumes:
      - $USERDIR/alertmanager/alertmanager.yml:/alertmanager.yml
    logging:
      options:
        max-size: 50m

  prometheus_speedtest:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: Speedtest
    hostname: speedtest
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 1
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    expose:
      - $SPEEDTEST_PORT:9798
    labels:
      - "traefik.enable=false"
    logging:
      options:
        max-size: 50m

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: Exporter-Radarr
    hostname: exporterr
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 3
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    command: ["exportarr", "radarr"]
    environment:
      TINI_SUBREAPER: "true"
      PORT: $RADARR_EX_PORT
      URL: "http://192.168.68.23:7878/"
      APIKEY: $RADARR_API_KEY
    expose:
      - $RADARR_EX_PORT
    labels:
      - "traefik.enable=false"
    logging:
      options:
        max-size: 50m

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: Exporter-Sonarr
    hostname: exporters
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 5
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    command: ["exportarr", "sonarr"]
    environment:
      TINI_SUBREAPER: "true"
      PORT: $SONARR_EX_PORT
      URL: "http://192.168.68.23:8989/"
      APIKEY: $SONARR_API_KEY
      ENABLE_EPISODE_QUALITY_METRICS: "false"
    expose:
      - $SONARR_EX_PORT
    labels:
      - "traefik.enable=false"
    logging:
      options:
        max-size: 50m

  tautulli-nsfk:
    image: tautulli/tautulli
    container_name: Tautulli-NSFK
    hostname: tautulli-nsfk
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 3
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETGID
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    ports:
      - $TAUTULLI_NSFK_PORT:8181
    labels:
      - "traefik.enable=false"
    volumes:
      - $USERDIR/tautulli/nsfk:/config:rw
    logging:
      options:
        max-size: 50m

  tautulli-multimedia:
    image: tautulli/tautulli
    container_name: Tautulli-Multimedia
    hostname: tautulli-mm
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 3
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETGID
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    ports:
      - $TAUTULLI_MM_PORT:8181
    labels:
      - "traefik.enable=false"
    volumes:
      - $USERDIR/tautulli/multimedia:/config:rw
    logging:
      options:
        max-size: 50m

  #----------------- GRAFANA
  Grafana:
    image: grafana/grafana:latest-ubuntu
    container_name: Grafana
    hostname: grafana
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 5
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - GF_INSTALL_PLUGINS=grafana-googlesheets-datasource,mtanda-google-calendar-datasource,marcusolsson-csv-datasource,camptocamp-prometheus-alertmanager-datasource,grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel,grafana-polystat-panel,grafana-singlestat-panel,macropower-analytics-panel,speakyourcode-button-panel,thiagoarrais-matomotracking-panel,marcusolsson-calendar-panel,integrationmatters-comparison-panel,briangann-gauge-panel,agenty-flowcharting-panel,marcusolsson-gantt-panel,mtanda-histogram-panel,michaeldmoore-multistat-panel,isaozler-paretochart-panel,corpglory-progresslist-panel,snuids-radar-panel,michaeldmoore-scatter-panel,mxswat-separator-panel,novatec-sdg-panel,snuids-trafficlights-panel,flant-statusmap-panel,auxmoney-waterfall-panel
    ports:
      - $GRAFANA_PORT:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.traefik.me`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana-tls.tls.domains[0].main=grafana.traefik.me"
      - "traefik.http.routers.grafana-tls.tls.domains[0].sans=grafana-*.traefik.me"
    volumes:
      - $USERDIR/grafana:/var/lib/grafana
    tmpfs:
      - /tmp
    logging:
      options:
        max-size: 50m

  Loki:
    image: grafana/loki:k73-88feda4-arm
    container_name: Loki
    hostname: loki
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 3
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 24m
    mem_reservation: 10m
    ports:
      - $LOKI_PORT:3100
    labels:
      - "traefik.enable=tfalse"
    environment:
      - user=$UID
    volumes:
      - $USERDIR/loki/loki-config.yml:/etc/loki/loki-config.yml

  Promtail:
    image: grafana/promtail:k73-88feda4-arm
    container_name: Promtail
    hostname: promtail
    restart: unless-stopped
    init: true
    read_only: true
    pids_limit: 3
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 24m
    mem_reservation: 10m
    labels:
      - "traefik.enable=false"
    environment:
      - user=$UID
    volumes:
      - /var/log:/var/log:ro
      - $USERDIR/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml

#----------------- COMMON
networks:
  default:
    external: true
    name: styx
