services:
  guacamole:
    image: oznu/guacamole:armhf
    container_name: Guacamole
    hostname: guacamole
    restart: unless-stopped
    init: true
    pids_limit: 5
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_SETGID
      - CAP_AUDIT_WRITE
      - CAP_KILL
      - CAP_NET_BIND_SERVICE
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 1.00
    mem_limit: 128m
    mem_reservation: 32m
    ports:
      - $GUACAMOLE_PORT:8080
    volumes:
      - $USERDIR/guacamole:/config
    logging:
      options:
        max-size: 50m

networks:
  default:
    external: true
    name: $DOCKER_NETW
