services:
#----- Homebridge
  homebridge:
    image: homebridge/homebridge:${HB_TAG:-latest}
    container_name: homebridge
    hostname: homebridge
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 400M
#        reservations:
#          cpus: '0.1'
#          memory: 80M
    environment:
      - TZ=$TZ
      - ENABLE_AVAHI=1
      - HOMEBRIDGE_CONFIG_UI=1
    volumes:
      - $USERDIR/homebridge:/homebridge
    labels:
      - autoheal:true
    network_mode: host
    logging:
      #syslog-address: "tcp://192.168.68.62:514"
      driver: json-file
      options:
        max-size: 10m
        max-file: 1
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s

#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true