services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:${DUCKDNS_TAG:-latest}
    container_name: DuckDNS
    hostname: duckdns
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    #    deploy:
    #      resources:
    #        limits:
    #          memory: 24M
    #        reservations:
    #          memory: 10M
    environment:
      - PUID=$UID
      - PGID=$GID
      - UMASK=022
      - SUBDOMAINS=$DUCKDNS_SUBDOMAINS
      - TOKEN=$DUCKDNS_TOKEN
      - LOG_FILE=false
    volumes:
      - $USERDIR/duckdns:/config:rw
    labels:
      - autoheal:true
    networks:
      - docker
    logging:
      options:
        max-size: 50m

  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:${SPEEDTEST_TAG:-latest}
    container_name: Speed-Test-Tracker
    hostname: speedtestracker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    #    deploy:
    #      resources:
    #        limits:
    #          memory: 24M
    #        reservations:
    #          memory: 10M
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TZ
    volumes:
      - $USERDIR/speedtestracker:/config:rw
    labels:
      - autoheal:true
    ports:
      - ${SPEEDTEST_WEBUI_PORT:-9443}:443
    networks:
      - docker
    logging:
      options:
        max-size: 50m

  uptime-kuma:
    image: louislam/uptime-kuma:${KUMA_TAG:-latest}
    container_name: UptimeKuma
    hostname: uptimekuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    #    deploy:
    #      resources:
    #        limits:
    #          memory: 24M
    #        reservations:
    #          memory: 10M
    environment:
      - PUID=$UID
      - PGID=$GID
      - NODE_ENV=production
      - DOCKER_MODS=$KUMA_MODS
      - TP_DOMAIN=$TP_DOMAIN
      - TP_SCHEME=$TP_SCHEME
      - TP_THEME=$TP_THEME
    volumes:
      - $USERDIR/uptime-kuma:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - autoheal:true
    ports:
      - ${KUMA_WEBUI_PORT:-3001}:3001
    networks:
      - docker
    logging:
      options:
        max-size: 50m

#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true
