---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push
    #tenant_id: tenant1

scrape_configs:
#----- LOCALHOST LOGS
- job_name: localhost
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

#----- DOCKER LOGS
#  - job_name: docker
#    static_configs:
#    pipeline_stages:
#      - docker: {}
#    labels:
#      job: docker
#      __path__: /var/lib/docker/containers/*/*-json.log
