services:
#----- MAUTIC
  database:
    image: powertic/percona-docker
    container_name: MauticDB
    hostname: mauticdb
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
#      resources:
#        limits:
#          memory: 64M
#        reservations:
#          memory: 24M
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=$MDB_ROOT_PW
    volumes:
      - $USERDIR/mautic/db:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    labels:
      - autoheal:true
    ports:
      - ${MDB_PORT:-3306}:3306
    networks:
      - mautic
    logging:
      options:
        #syslog-address: "tcp://192.168.68.62:514"
        max-size: 50m
        max-file: 10

  mautic:
    image: mautic/mautic:${MAUTIC_TAG:-latest}
    container_name: Mautic
    hostname: mautic
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
#      resources:
#        limits:
#          memory: 64M
#        reservations:
#          memory: 24M
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=$MAUTIC_DB_USER
      - MAUTIC_DB_PASSWORD=$MAUTIC_DB_PASSWORD
      - MAUTIC_DB_NAME=$MAUTIC_DB_NAME
      - MAUTIC_ADMIN_USERNAME=$MADMIN_UN
      - MAUTIC_ADMIN_PASSWORD=$MADMIN_PW
      - MAUTIC_ADMIN_EMAIL=$MADMIN_MAIL
    volumes:
      - $USERDIR/mautic/mautic:/var/www/html:rw
      - /etc/localtime:/etc/localtime:ro
    labels:
      - autoheal:true
    ports:
      - ${MAUTIC_PORT:-8080}:80
    networks:
      - mautic
      - docker
    depends_on:
      - database
    logging:
      options:
        #syslog-address: "tcp://192.168.68.62:514"
        max-size: 50m
        max-file: 10

#----- GRAV
  grav:
    image: lscr.io/linuxserver/grav:${GRAV_TAG:-latest}
    container_name: Grav
    hostname: grav
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
#      resources:
#        limits:
#          memory: 64M
#        reservations:
#          memory: 24M
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TZ
    volumes:
      - $USERDIR/grav:/config
    labels:
      - autoheal:true
    ports:
      - ${GRAV_PORT:-80}:80


#----------------- NETWORKING
networks:
  mautic:
    name: $MAUTIC_NET
    external: true
  docker:
    name: $DOCKER_NET
    external: true