services:
  cloudflared:
    image: erisamoe/cloudflared:${CLOUDFLARED_TAG:-latest}
    container_name: Cloudflared
    hostname: cloudflared
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TOKEN}
    labels:
      - autoheal:true
    networks:
      - docker
    logging:
      options:
        max-size: 50m

#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true
