version: "2"

services:
  telegraf:
    image: telegraf:[1.16.2]
    restart: always
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock/:ro
      - [/home/docker/persistent-storage/telegraf/]telegraf-config.conf:/etc/telegraf/telegraf.conf/:ro