services:
  bookstack:
    image: linuxserver/bookstack:${BOOKS_TAG:-latest}
    container_name: Bookstack
    hostname: bookstack
    restart: unless-stopped
    init: true
    pids_limit: 2
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_MKNOD
      - CAP_SETGID
      - CAP_SYS_CHROOT
      - CAP_AUDIT_WRITE
      - CAP_DAC_OVERRIDE
      - CAP_FSETID
      - CAP_KILL
      - CAP_NET_RAW
      - CAP_SETPCAP
      - CAP_NET_BIND_SERVICE
      - CAP_SETFCAP
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DB_HOST=$BOOKS_DB_HOST
      - DB_PORT=${BOOKS_DB_PORT:-3306}
      - DB_USER=$BOOKS_DB_USER
      - DB_PASS=$BOOKS_DB_PW
      - DB_DATABASE=$BOOKS_DB
      - APP_URL=$BOOKS_URL
    volumes:
      - $USERDIR/app:/config
    ports:
      - ${BOOKS_PORT:-8070}:443
    depends_on:
      - db
    networks:
      - default
      - docker
    logging:
      options:
        max-size: 50m

  db:
    image: linuxserver/mariadb:${BOOKS_DB_TAG:-latest}
    container_name: Bookstack_DB
    hostname: bookstack-db
    restart: unless-stopped
    init: true
    pids_limit: 2
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_MKNOD
      - CAP_SETGID
      - CAP_SYS_CHROOT
      - CAP_AUDIT_WRITE
      - CAP_DAC_OVERRIDE
      - CAP_FSETID
      - CAP_KILL
      - CAP_NET_RAW
      - CAP_SETPCAP
      - CAP_NET_BIND_SERVICE
      - CAP_SETFCAP
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Toronto}
      - MYSQL_ROOT_PASSWORD=$BOOKS_DB_ROOT_PW
      - MYSQL_DATABASE=$BOOKS_DB
      - MYSQL_USER=$BOOKS_DB_USER
      - MYSQL_PASSWORD=$BOOKS_DB_PW
    volumes:
      - $USERDIR/db:/config
    ports:
      - ${BOOKS_DB_PORT:-3306}:3306
    networks:
      - default
    logging:
      options:
        max-size: 50m


#----------------- NETWORKING
networks:
  default:
    name: $DEFAULT_NET
    external: true
  docker:
    name: $DOCKER_NET
    external: true
