ersion: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: Prometheus
    restart: unless-stopped
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - /home/grafana/prometheus:/etc/prometheus
      - /home/grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
