services:
  app:
    image: jc21/nginx-proxy-manager:$NPM_TAG
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    init: true
    read_only: false
    pids_limit: 2
    privileged: false
    #cpus: 0.10
    #mem_limit: 24m
    #mem_reservation: 10m
    security_opt:
      - no-new-privileges:true
    environment:
      DB_MYSQL_HOST: $NPM_DB_HOST
      DB_MYSQL_PORT: $NPM_DB_PORT
      DB_MYSQL_USER: $NPM_DB_USER
      DB_MYSQL_PASSWORD: $NPM_DB_PW
      DB_MYSQL_NAME: $NPM_DB_NAME
      DISABLE_IPV6: $IPV6
    networks:
      - default
      - docker
    ports:
      - $NPM_PORT1:80
      - $NPM_PORT2:81
      - $NPM_PORT3:443
    volumes:
      - $USERDIR/data:/data
      - $USERDIR/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    logging:
      options:
        max-size: 50m

  db:
    image: jc21/mariadb-aria:$DB_TAG
    container_name: npm-db
    hostname: npm-db
    restart: unless-stopped
    init: true
    read_only: false
    pids_limit: 2
    privileged: false
    #cpus: 0.10
    #mem_limit: 24m
    #mem_reservation: 10m
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_ROOT_PASSWORD: $NPM_ROOT_PW
      MYSQL_DATABASE: $NPM_DB_NAME
      MYSQL_USER: $NPM_DB_USER
      MYSQL_PASSWORD: $NPM_DB_PW
    networks:
      - default
      - docker
    ports:
      - $NPM_DB_PORT:3306
    volumes:
      - $USERDIR/db:/var/lib/mysql
    logging:
      options:
        max-size: 50m

#----------------- COMMON
networks:
  docker:
    external: true
    name: $DOCKER_NET
  default:
    internal: true
