services:
  #============= DASHBOARDS
  main:
    image: lissy93/dashy:$DASHY_TAG
    container_name: DashyMain
    hostname: dashy-main
    restart: unless-stopped
    init: true
    pids_limit: 2
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      - UID=$PUID
      - GID=$PGID
      - NODE_ENV=$ENV
      - IS_DOCKER=true
      #- SSL_PRIV_KEY_PATH=/etc/ssl/certs/dashy-priv.key
      #- SSL_PUB_KEY_PATH=/etc/ssl/certs/dashy-pub.pem
    ports:
      - $DASHY_PORT1:80
      #- $DASHY_SSL1:443
    volumes:
      - $USERDIR/main-conf.yml:/app/public/conf.yml
      - $USERDIR/icons/Icons/png:/app/public/item-icons:ro
      - $USERDIR/main-public/trivmviratvs.png:/app/public/favicon.ico
      #- $USERDIR/custom-theme.scss:/app/src/styles/user-defined-themes.scss:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      options:
        max-size: 50m

  admin:
    image: lissy93/dashy:$DASHY_TAG
    container_name: DashyAdmin
    hostname: dashy-admin
    restart: unless-stopped
    init: true
    pids_limit: 2
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      - UID=$PUID
      - GID=$PGID
      - NODE_ENV=$ENV
      - IS_DOCKER=true
      #- SSL_PRIV_KEY_PATH=/etc/ssl/certs/dashy-priv.key
      #- SSL_PUB_KEY_PATH=/etc/ssl/certs/dashy-pub.pem
    ports:
      - $DASHY_PORT2:80
      #- $DASHY_SSL2:443
    volumes:
      - $USERDIR/admin-conf.yml:/app/public/conf.yml
      - $USERDIR/icons/Icons/png:/app/public/item-icons:ro
      #- $USERDIR/admin-public/:/app/public/favicon.ico
      #- $USERDIR/custom-theme.scss:/app/src/styles/user-defined-themes.scss:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      options:
        max-size: 50m

  bookmarks:
    image: lissy93/dashy:$DASHY_TAG
    container_name: DashyBookmarks
    hostname: dashy-bookmarks
    restart: unless-stopped
    init: true
    pids_limit: 2
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      - UID=$PUID
      - GID=$PGID
      - NODE_ENV=$ENV
      - IS_DOCKER=true
      #- SSL_PRIV_KEY_PATH=/etc/ssl/certs/dashy-priv.key
      #- SSL_PUB_KEY_PATH=/etc/ssl/certs/dashy-pub.pem
    ports:
      - $DASHY_PORT3:80
      #- $DASHY_SSL3:443
    volumes:
      - $USERDIR/bookmarks-conf.yml:/app/public/conf.yml
      - $USERDIR/icons/Icons/png:/app/public/item-icons:ro
      #- $USERDIR/bookmarks-public/:/app/public/favicon.ico
      #- $USERDIR/custom-theme.scss:/app/src/styles/user-defined-themes.scss:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      options:
        max-size: 50m

#============= COMMON
networks:
  docker:
    external: true
    name: $DOCKER_NET
