services:
#----- DPM INC
  kanboard:
    image: ghcr.io/kanboard/kanboard:${KANBOARD_TAG:-latest}
    container_name: Kanboard
    hostname: kanboard
    restart: unless-stopped
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 24M
        reservations:
          cpus: '0.05'
          memory: 6M
    environment:
      - PLUGIN_INSTALLER=true
    volumes:
      - $USERDIR/dpm/kanboard:/var/www/app/data:rw
      - $USERDIR/dpm/kanboard/plugins:/var/www/app/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    labels:
      - autoheal:true
    ports:
      - ${KANBOARD_PORT:-80}:80/tcp
    networks:
      - dpm
    logging:
      options:
        #syslog-address: "tcp://192.168.68.62:514"
        max-size: 50m
        max-file: 10


#----- GRAV
  grav:
    image: lscr.io/linuxserver/grav:${GRAV_TAG:-latest}
    container_name: Grav
    hostname: grav
    read_only: false
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
#      resources:
#        limits:
#          memory: 64M
#        reservations:
#          memory: 24M
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TZ
    volumes:
      - $USERDIR/grav:/config
    labels:
      - autoheal:true
    ports:
      - ${GRAV_PORT:-80}:80


#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true
  dpm:
    name: $DPM_NET
    external: true