services:
  netdata:
    image: netdata/netdata
    container_name: Netdata
    hostname: netdata
    restart: unless-stopped
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - NETDATA_CLAIM_TOKEN=xV2wmUTpZWbhL3AQrMOUd7e7JQAb6_8nnmGfiHjQWDrKvDU0KZwA6kPfr71s8l5avxwZehR3q9y-LLBzb6OBWD6mg1vWth0NhtnEy0DMexSg4m6wTbDaEdP_1L0qg340wzq76-I
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=55e56f8f-15de-4dbf-9232-4ab059b558cf
    volumes:
      - /volume1/docker/netdata/config:/etc/netdata
      - /volume1/docker/netdata/lib:/var/lib/netdata
      - /volume1/docker/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
