services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:${OV_TAG:-latest}
    container_name: Overseerr
    hostname: overseer
    restart: unless-stopped
    init: true
    read_only: false
    pids_limit: 3
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - $USERDIR/overseerr:/config:rw
    ports:
      - ${OV_PORT:-5055}:5055
    logging:
      options:
        max-size: 50m

  #------------------ THE "ARRs"
  prowlarr:
    image: lsrc.io/linuxserver/prowlarr:${PROWL_TAG:-develop}
    container_name: Prowlarr
    hostname: prowlarr
    restart: unless-stopped
    init: true
    read_only: false
    pids_limit: 3
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_SETGID
      - CAP_DAC_OVERRIDE
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.05
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DOCKER_MODS=${DOCKER_MODS:-ghcr.io/gilbn/theme.park:prowlarr}
      - TP_THEME=plex
    volumes:
      - $USERDIR/prowlarr:/config:rw
    ports:
      - ${PROWL_PORT:-9696}:9696
    logging:
      options:
        max-size: 50m

  readarr:
    image: lscr.io/linuxserver/readarr:${READ_TAG:-latest}
    container_name: Readarr
    hostname: readarr
    restart: unless-stopped
    init: true
    read_only: false
    pids_limit: 5
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_SETGID
      - CAP_DAC_OVERRIDE
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=$TZ
      - DOCKER_MODS=${READ_MODS:-ghcr.io/gilbn/theme.park:readarr}
      - TP_THEME=plex
    volumes:
      - $USERDIR/readarr:/config:rw
      - $USERDIR/downloads/books:/downloads:rw
    ports:
      - ${RAD_PORT:-8787}:8787
    logging:
      options:
        max-size: 50m

  radarr:
    image: lscr.io/linuxserver/radarr:${RAD_PORT:-latest}
    container_name: Radarr
    hostname: radarr
    restart: unless-stopped
    init: true
    read_only: false
    pids_limit: 5
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_SETGID
      - CAP_DAC_OVERRIDE
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DOCKER_MODS=${RAD_MODS:-ghcr.io/gilbn/theme.park:radarr}
      - TP_THEME=plex
    volumes:
      - $USERDIR/radarr:/config:rw
      - $USERDIR/downloads:/data:rw
    ports:
      - ${RAD_PORT:-7878}:7878
    logging:
      options:
        max-size: 50m

  sonarr:
    image: lscr.io/linuxserver/sonarr:${SON_TAG:-latest}
    container_name: Sonarr
    hostname: sonarr
    restart: unless-stopped
    init: true
    read_only: false
    pids_limit: 5
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_SETGID
      - CAP_DAC_OVERRIDE
      - CAP_SETUID
    security_opt:
      - no-new-privileges:true
    cpus: 0.5
    mem_limit: 24m
    mem_reservation: 10m
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      #- DOCKER_MODS=${SON_MODS:-ghcr.io/gilbn/theme.park:sonarr}
      #- TP_THEME=plex
    volumes:
      - $USERDIR/sonarr:/config:rw
      - $USERDIR/downloads:/data:rw
    ports:
      - ${SON_PORT:8989}:8989
    logging:
      options:
        max-size: 50m

#------------------ COMMON
networks:
  default:
    external: true
    name: $DOCKER_NET
