services:
  glances:
    image: nicolargo/glances:${GLANCES_TAG:-alpine-latest}
    container_name: Glances
    hostname: glances
    read_only: false
    privileged: false
    pid: host
    security_opt:
      - no-new-privileges:true
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '0.15'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 30M
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - $USERDIR/glances/glances.conf:/glances/conf/glances.conf:rw
    labels:
      - autoheal:true
    ports:
      - ${GLANCES_PORTS:-61208-61209}:61208-61209
    networks:
      - docker
    logging:
      options:
        #syslog-address: "tcp://192.168.68.62:514"
        max-size: 50m
        max-file: 10


#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true
