services:
  cloudflared:
    image: erisamoe/cloudflared:${CLOUDFLARED_TAG:-latest}
    container_name: Cloudflared
    hostname: cloudflared
    restart: unless-stopped
    read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
    command: tunnel --no-autoupdate run
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 30M
        reservations:
          cpus: '0.025'
          memory: 20M
    environment:
      - TUNNEL_TOKEN=${CF_TOKEN}
    labels:
      - autoheal:true
    networks:
      - docker
    logging:
      options:
        max-size: 50m

  uptime-kuma:
    image: louislam/uptime-kuma:${KUMA_TAG:-latest}
    container_name: UptimeKuma
    hostname: uptimekuma
    restart: unless-stopped
    read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 180M
        reservations:
          cpus: '0.1'
          memory: 80M
    environment:
      - PUID=$UID
      - PGID=$GID
      - NODE_ENV=production
      - DOCKER_MODS=$KUMA_MODS
      - TP_DOMAIN=$TP_DOMAIN
      - TP_SCHEME=$TP_SCHEME
      - TP_THEME=$TP_THEME
    volumes:
      - $USERDIR/uptime-kuma:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - autoheal:true
    ports:
      - ${KUMA_WEBUI_PORT:-3001}:3001
    networks:
      - docker
    logging:
      options:
        max-size: 50m

#----------------- NETWORKING
networks:
  docker:
    name: $DOCKER_NET
    external: true
